[package]
name = "rssreader"
version = "0.1.0"
authors = ["U-C-S <ucs3721@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindings = { path = "bindings" }
windows="0.10.0"