[package]
name = "algorithms"
version = "0.2.0"
authors = ["U-C-S <ucs3721@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
text_io = "0.1.8"